### ISSUE TITLE
Issue with new 0.9.0 version - Some tests are repeated in different groups and some tests are not even being run in any group

### ISSUE THREAD

**Issue by marcodicro-dp** [jerry-git/pytest-split#100]
With the new version, I detected some tests were not being run.

Analyzing the logs, I realized some tests were being run twice or even 4 times in different groups. And also many tests were not being run.

When I pin the version to 0.8.2 the issue goes away.
That works for me now but any chance to get a proper fix for v0.9.0?

**Comment by jerry-git** [comment]
Hey! Thanks for the report! This sounds surprising as it seems that there actually weren't any logical changes between 0.8.2 and 0.9.0: https://github.com/jerry-git/pytest-split/compare/0.8.2...0.9.0 🤔

Could you share some logs or a link to a test run? If it's a closed source project, could you share a test_durations file (feel free to anonymise the test names)?

**Comment by marcodicro-dp** [comment]
Yes! It also sounded surprising to me when I noticed this and I saw no major changes in the changelog.

First of all, I want to say that the "tests being repeated in different groups" problem is not happening anymore. That was happening because my test durations file was wrong (it had the test paths expressed relative to a different directory than the expected one for this workflow). I now have the test durations duplicated, once with the full path (relative to root as I need for this workflow e.g. `test/example_app3/tests/example_test.py::SomeTest::test_1`) and once with the path relative to a subdirectory (I need this one for another workflow. e.g. `tests/example_test.py::SomeTest::test_1`).

Now that test paths are OK, it works much better, but I still see a difference in behavior between the versions:

- v0.9.0 -> 6264 tests run (and no repetitions)
- v0.8.2 -> 6359 tests run (and no repetitions)

So still 95 tests were not run with v0.9.0.

I used exactly the same test durations file for both runs, and not storing test durations during the run (because I run groups sequentially, so storing durations could affect following groups).

Closed source repo, so trying not to share more than I should. Hope that's enough. However, let me know if you need extra info and I'll do my best to add it. 

Logs and test durations here, added you as viewer @jerry-git : https://drive.google.com/drive/folders/1_6TwoP6ebR2QwjxJbE3Pr-XmH3g8UeUG?usp=sharing

Thank you so much in advance for your help!

**Comment by marcodicro-dp** [comment]
Discard this issue, the problem was related to mixing pytest-split with testmon in a single command:
`pytest tests --testmon-noselect --splits 25 --group 1 -v --ignore=tests/analytics_es_tests/ --rootdir=/__w/sample_repo/sample_repo/test/app/../..`

Already raised a ticket about that: https://github.com/jerry-git/pytest-split/issues/93
