### ISSUE TITLE
pytest.mark.parametrize potential weird interaction

### ISSUE THREAD

**Issue by michaelgmiller1** [jerry-git/pytest-split#102]
We are getting error code 5 (no tests ran) on our test runners.

However, we have many more tests than runners, and no runners are running less than 10 tests. My suspicion is that we have a few slow tests with `pytest.mark.parametrize` - and these are not being split up across runners.

Does a test with `pytest.mark.parametrize` get split up into different groups?

**Comment by michaelgmiller1** [comment]
I tested locally, and it seems like the tests are split out onto separate runners. I suspect we are seeing the error code 5 simply due to edge overflow, where it's not possible to efficiently allocate tests to an extra runner.

**Comment by jerry-git** [comment]
Could it be the same as in https://github.com/jerry-git/pytest-split/issues/95?

**Comment by michaelgmiller1** [comment]
> Could it be the same as in #95?

Yep, I think it is!
