### ISSUE TITLE
Splitting takes too long

### ISSUE THREAD

**Issue by ma-sadeghi** [jerry-git/pytest-split#48]
I just noticed that the splitting part takes too long (~1 min for my case). Is this expected? To reproduce, clone [porespy](https://github.com/PMEAL/porespy), `cd` to `porespy` folder, and run the following command:

```bash
pytest test/ --splits 3 --group 1 --durations-path test/fixtures/.test_durations_unit
```

**Comment by jerry-git** [comment]
It's not pytest-split, it's the test collection which is slow in that project 🙂  I assume there are some super heavy fixtures or such?
![Screenshot 2022-03-13 at 14 12 27](https://user-images.githubusercontent.com/30327563/158058977-202d4af0-403f-4521-b361-1a16a03a2219.png)

**Comment by jerry-git** [comment]
The problem with `porespy` project is that it runs all the integration tests during collection as those are not wrapped into functions (i.e. those are not tests but scripts which run when the module is loaded). This is evident if you run e.g. `pytest test/integration` 🙂 

![Screenshot 2022-03-13 at 14 35 36](https://user-images.githubusercontent.com/30327563/158059603-92aa758a-d321-4908-8c2e-d84f39458266.png)

**Comment by ma-sadeghi** [comment]
Thank you so much for your super helpful reply! I just wrapped them in a few functions, and sure enough, the test collection is almost instant!
