### ISSUE TITLE
ability to load different files and store seperate duration files

### ISSUE THREAD

**Issue by indiVar0508** [jerry-git/pytest-split#90]
Hi 
i have a case where i generate duration file in seperate workflow and i also generate duration file on my pr builds which i consume for seperate usecase
i have `.test_durations` file which i want pytest-split to use to make splits of groups

currently i am using `--store-durations --durations-path=.my-custom-path-for-diff-usecase`
this makes pytest-split to look for this `.my-custom-path-for-diff-usecase` which is not there.

is there a way to tell pytest-split to inform to read from one file and write to other
one way could be `--store-durations-path=...` which is only to be written and not read?

i see pytest-split loads config at this point, https://github.com/jerry-git/pytest-split/blob/master/src/pytest_split/plugin.py#L128, is it possible to add an optional parameter load_cache_duration, which if provided should load that file and not store path?

Thanks

**Comment by jerry-git** [comment]
I think this is a bit out of scope for pytest-split. However, I believe you could achieve the same by adding the logic in your CI or wherever you have this use case. For example, you could store a copy of the original durations file before executing pytest, do what you need with the fresh durations file after the test run, and finally restore the copy of the original.
