### ISSUE TITLE
Single command to run groups and collect output

### ISSUE THREAD

**Issue by ddorian** [jerry-git/pytest-split#92]
I didn't find any. Is there a command that will basically run several groups and collect output and display it? Needed so I can run locally with 1 command to speedup tests.

**Comment by jerry-git** [comment]
If the motivation is to run the full test suite split into _n_ sub suites running in parallel in local environment, I believe you could do something like `pytest --splits 3 --group 1 & pytest --splits 3 --group 2 & pytest --splits 3 --group 3`.

However, if this is about speeding up local runs, I'd recommend having a look at pytest-xdist.

**Comment by ddorian** [comment]
True, but pytest-xdist doesn't work with gevent https://github.com/pytest-dev/pytest-xdist/issues/1069
